In [1]:
import numpy as np

# 1d ndarray

In [2]:
mylist1 = [11,22,33,44,55,66]
print(mylist1)
print(type(mylist1))

[11, 22, 33, 44, 55, 66]
<class 'list'>


In [3]:
n1 = np.array(mylist1)
print(n1)
print(type(n1))

[11 22 33 44 55 66]
<class 'numpy.ndarray'>


In [4]:
n1.shape

(6,)

In [5]:
n1.ndim

1

In [6]:
n1.itemsize

4

In [7]:
n1.size

6

In [8]:
total_mem_occupied = n1.itemsize * n1.size
print(total_mem_occupied)

24


In [9]:
n1

array([11, 22, 33, 44, 55, 66])

In [10]:
n1 = np.array(list(range(2,30)))
print(n1)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29]


In [11]:
n1[15]

17

In [12]:
n1[-5]

25

In [13]:
n1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
n1[3:16:3]

array([ 5,  8, 11, 14, 17])

In [15]:
n1[[10,4,7,-15,5,-11]]

array([12,  6,  9, 15,  7, 19])

In [16]:
n1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
n1 = np.array(list(range(30)))
n2 = np.array(list(range(40,70)))
n3 = n1 + n2

print(n1)
print(n2)
print(n3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
 64 65 66 67 68 69]
[40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86
 88 90 92 94 96 98]


In [18]:
n1 = np.arange(20)
print(n1)
print(type(n1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [19]:
n1 = np.arange(20,30)
print(n1)
print(type(n1))

[20 21 22 23 24 25 26 27 28 29]
<class 'numpy.ndarray'>


In [20]:
n1 = np.arange(10,100,3)
print(n1)
print(type(n1))

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]
<class 'numpy.ndarray'>


# 2d ndArray

In [21]:
mylist2 = [[1,2,3,4],[11,22,33,44],[111,222,333,444]]
print(mylist2)

[[1, 2, 3, 4], [11, 22, 33, 44], [111, 222, 333, 444]]


In [22]:
n34 = np.array(mylist2)
print(n34)

[[  1   2   3   4]
 [ 11  22  33  44]
 [111 222 333 444]]


In [23]:
n34.ndim

2

In [24]:
x = n34.shape
print(x)
print(type(x))

(3, 4)
<class 'tuple'>


In [25]:
n68 = np.arange(6*8).reshape(6,8)
print(n68)
print(type(n68))
print(n68.shape)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
<class 'numpy.ndarray'>
(6, 8)


In [ ]:
n34a = np.arange(10,22).reshape(3,4)
n34b = np.arange(100,100+12).reshape(3,4)
n34c = n34a * n34b
print(n34a)
print(n34b)
print(n34c)

In [ ]:
n68 = np.arange(48).reshape(6,8)
print(n68)

In [ ]:
n86 = n68.reshape(8,6)
print(n86)

In [ ]:
n3_16 = n86.reshape(3,16)
print(n3_16)

In [ ]:
n34 = np.arange(1,12+1).reshape(3,4)
n43 = np.arange(1,12+1).reshape(4,3)
print(n34)
print(n43)

In [ ]:
n33 = n34.dot(n43)
print(n33)

# 2D Access

In [ ]:
n68 = np.arange(100,100+(6*8)).reshape(6,8)
print(n68)

In [ ]:
n68[0]

In [ ]:
n68[5]

In [ ]:
n68[-1]

In [ ]:
n68

In [ ]:
n68[0,0]

In [ ]:
n68[4,6]

In [ ]:
n68[0,-1]

In [ ]:
n68[-1,0]

In [ ]:
n68[-1,-1]

In [ ]:
print(n68)

In [ ]:
n68[1:4]

In [ ]:
n68[1::2]

In [ ]:
n = n68[1:4, 2:6]
print(n)
print(type(n))
print(n.shape)

In [ ]:
print(n68)

In [ ]:
n68[:,3]

In [ ]:
n1 = n68[:,3:6:2]
print(n1)
print(n1.shape)

In [ ]:
n1 = n68[[1,5,3],[2,6,4]]  #n68[1,2], n68[5,6], n68[3,4]
print(n1)

In [ ]:
n1 = n68[[1,5,3],[[2],[6],[4]]]
print(n1)

In [ ]:
print(n68)

In [ ]:
n68[1:5,[2,4,6]]

In [ ]:
n1= n68[1:5,3]
print(n1)
print(n1.shape)

In [ ]:
print(n68)

In [ ]:
n1= n68[1:5,[3]]
print(n1)
print(n1.shape)

In [ ]:
print(n68)

In [ ]:
n86 = n68.T
print(n86)
print(n86.shape)

# Predefined Functions

In [ ]:
n86

In [ ]:
n86.mean()

In [ ]:
n86[0].mean()

In [ ]:
n86[:,2].mean()

In [ ]:
n86[1:5].mean()

In [ ]:
n1 = n86[1:5]
print(n1.mean())

In [ ]:
n68.max()

In [ ]:
n68.min()

In [ ]:
n68.var()

In [ ]:
n68.std()

In [ ]:
n68.sum()

In [ ]:
np.prod(n68)

In [ ]:
n68

In [ ]:
np.median(n68)

In [ ]:
n68z = np.zeros((6,8),dtype=np.int32)

In [ ]:
print(n68z)

In [ ]:
n68z.dtype

In [ ]:
n68o = np.ones((6,8))
print(n68o)

In [ ]:
n66i = np.identity(6)
print(n66i)

In [ ]:
n66i = np.eye(6,k=0,dtype=np.int16)
print(n66i)

In [ ]:
n34f = np.full((3,4),-22)
print(n34f)

In [ ]:
n34e = np.empty((3,4))
print(n34e)

In [ ]:
np.where(n34e)

In [ ]:
rci = np.where(n34e)
for ri,ci in zip(rci[0],rci[1]):
    n34e[ri,ci] = 0
print(n34e)

In [ ]:
n34r = np.random.randint(low=-5, high=3, size=(3,4))
print(n34r)

In [ ]:
n1k2ka = np.random.rand(50,50)
n1k2kb = np.random.rand(50,50)

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(n1k2ka,n1k2kb)
plt.show()

# Stack

In [ ]:
n43 = np.random.randint(low=10,high=20,size=(4,3))
n46 = np.random.randint(low=10,high=20,size=(4,6))
n42 = np.random.randint(low=10,high=20,size=(4,2))
print(n43)
print(n46)

In [ ]:
nhs = np.hstack((n43,n46,n42))
print(nhs)

In [ ]:
print(n43.shape)
print(n46.shape)
print(n42.shape)
print(nhs.shape)

In [ ]:
n68 = np.random.randint(low=5,high=20,size=(6,8))
print(n68)

In [ ]:
nhsp = np.hsplit(n68,4)
print(nhsp)

In [ ]:
print(type(nhsp))
print(len(nhsp))
for item in nhsp:
    #print(item)
    print(item.shape)

In [ ]:
nhsp = np.hsplit(n68,[1,4,6])
#print(nhsp)
print(type(nhsp))
print(len(nhsp))
for item in nhsp:
    #print(item)
    print(item.shape)

# Broadcasting

In [ ]:
n34 = np.arange(12).reshape(3,4)
n34a = n34+22
print(n34a)

In [ ]:
n34 = np.arange(12).reshape(3,4)
n14 = np.arange(4).reshape(1,4)
n = n34+n14
print(n)

In [ ]:
n34 = np.arange(12).reshape(3,4)
n31 = np.arange(3).reshape(3,1)
n = n34+n31
print(n)

In [ ]:
n8 = np.random.randint(8,size=(8,))
print(n8)

In [ ]:
n8 = np.array([9,3,6,4,8,2,1,5])
norder = np.argsort(n8)
nrank = np.argsort(norder)
print(n8)
print(norder)
print(nrank)

# Conditional Access

In [ ]:
n68 = np.random.randint(low=1,high=20,size=(6,8))
print(n68)

In [ ]:
mask = n68 > 10
print(mask)

In [ ]:
n = n68[mask]
print(n)

In [ ]:
np.unique(n)

# 3D array

In [226]:
n345 = np.arange(3*4*5).reshape(3,4,5)
print(n345)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [229]:
print(n345)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [232]:
print(n345[2,3,4])   #row_index,ci,di
print(n345[1:2,1:3,2:4])   #row_slice, col_s, depth_s
print(n345[[1,2,1],[2,3,1],[3,4,2]])  #row_vector, col_v, depth_v

59
[[[27 28]
  [32 33]]]
[33 59 27]


# view and copy

In [ ]:
n34 = np.random.randint(15,size=(3,4))
print(n34)

In [ ]:
ntf = n34

In [ ]:
print(ntf)

In [ ]:
n34[1,2] 

In [ ]:
n34[1,2] = 444

In [ ]:
print(n34)

In [ ]:
print(ntf)

In [ ]:
print(n34)

In [ ]:
ntf = n34.copy()

In [ ]:
print(ntf)

In [ ]:
n34[1,2]

In [ ]:
n34[1,2] = 888

In [ ]:
print(n34)

In [ ]:
print(ntf)

# stack

In [243]:
n1 = np.arange(2,11,2)
n2 = np.arange(22,31,2)
print(n1)
print(n2)

[ 2  4  6  8 10]
[22 24 26 28 30]


In [245]:
n = np.stack((n1,n2),axis=0)
print(n)
print(n.shape)

[[ 2  4  6  8 10]
 [22 24 26 28 30]]
(2, 5)


In [246]:
n = np.stack((n1,n2),axis=1)
print(n)
print(n.shape)

[[ 2 22]
 [ 4 24]
 [ 6 26]
 [ 8 28]
 [10 30]]
(5, 2)


# col_stack

In [248]:
n1 = np.arange(2,11,2)
n2 = np.arange(22,31,2)
print(n1)
print(n2)

[ 2  4  6  8 10]
[22 24 26 28 30]


In [251]:
nc = np.column_stack((n1,n2))
print(nc)

[[ 2 22]
 [ 4 24]
 [ 6 26]
 [ 8 28]
 [10 30]]


# Linear Space

In [256]:
nums = np.linspace(1,11,5)
print(nums)
print(len(nums))
print(list(nums))

[ 1.   3.5  6.   8.5 11. ]
5
[1.0, 3.5, 6.0, 8.5, 11.0]


In [254]:
nums = np.linspace(1,11,5,endpoint=False)
print(nums)

[1. 3. 5. 7. 9.]


In [257]:
print(n68)

[[ 4  6  1 19 12  5 14  9]
 [16 11  7 12  5  4  1 10]
 [15 17  9  7  7 17 17 10]
 [10 11 10 15  3 15  7  9]
 [10  3 17  8 13 17 10 14]
 [ 1  5 12  6 10 18  5 19]]


In [258]:
n68.ravel()

array([ 4,  6,  1, 19, 12,  5, 14,  9, 16, 11,  7, 12,  5,  4,  1, 10, 15,
       17,  9,  7,  7, 17, 17, 10, 10, 11, 10, 15,  3, 15,  7,  9, 10,  3,
       17,  8, 13, 17, 10, 14,  1,  5, 12,  6, 10, 18,  5, 19])

In [261]:
n = np.ravel(n68)
print(n)
print(type(n))
print(n.shape)

[ 4  6  1 19 12  5 14  9 16 11  7 12  5  4  1 10 15 17  9  7  7 17 17 10
 10 11 10 15  3 15  7  9 10  3 17  8 13 17 10 14  1  5 12  6 10 18  5 19]
<class 'numpy.ndarray'>
(48,)


In [262]:
n = np.identity(6)

In [263]:
print(n)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [264]:
n[n==0]=21
print(n)

[[ 1. 21. 21. 21. 21. 21.]
 [21.  1. 21. 21. 21. 21.]
 [21. 21.  1. 21. 21. 21.]
 [21. 21. 21.  1. 21. 21.]
 [21. 21. 21. 21.  1. 21.]
 [21. 21. 21. 21. 21.  1.]]
